### ISSUE TITLE
Price Slider - sliderElement.slider is not a function

### ISSUE THREAD

**Issue by gyduxa** [mageplaza/magento-2-ajax-layered-navigation#34]
On the products page, the price intervals appear (without slider) if I deactivate the mageplaza layered navigation.

Price slider deactivated:
<img width="159" alt="price-without-slide" src="https://user-images.githubusercontent.com/5487711/177766719-67462018-13bc-44a3-9396-5566b808b005.png">

Price slider activated:
<img width="165" alt="no-price" src="https://user-images.githubusercontent.com/5487711/177766710-77d974e2-6382-4af6-ad58-fad88b9425f7.png">

When I activate the mageplaza layered navigation it disappears, the HTML to the slider appears on source code but there's an error on the console: "sliderElement.slider is not a function"

![image](https://user-images.githubusercontent.com/5487711/177766230-1abee31b-3f4a-459b-b76c-807b303cf62d.png)

![image](https://user-images.githubusercontent.com/5487711/177765972-7d78054e-316f-4d02-b6e9-b93b6961931a.png)

The error on the console:

<img width="306" alt="error" src="https://user-images.githubusercontent.com/5487711/177766449-d50ecfbc-9260-4343-a08e-fd4e07f89ad4.png">

The beginning of the file on the console, doesn't have jquery/ui which is called on the layer.js file:

<img width="300" alt="ui-missing" src="https://user-images.githubusercontent.com/5487711/177766507-e773fb54-0a87-466d-9855-2838e5261469.png">

![image](https://user-images.githubusercontent.com/5487711/177766933-071ed697-c4ce-458c-b479-32175c4d8897.png)

On this page: https://www.mageplaza.com/magento-2-layered-navigation-extension/price-slider.html , the last printscreen shows a tab "Layered Navigation Properties" that I don't have.

My price attribute doesn't have the last tab:
<img width="785" alt="mageplaza-layered-navigation" src="https://user-images.githubusercontent.com/5487711/177765923-1a2c7fad-c7a8-449e-afec-04181d94fb4b.png">

I've upgraded the AjaxLayer from 1.4.5 to 1.4.12 (LayeredNavigation from 1.0.5 to 4.0.5).

![image](https://user-images.githubusercontent.com/5487711/177767295-6f84cca3-e81d-4fa9-8d63-47d9a1ea7e5e.png)

Thank you

**Comment by gyduxa** [comment]
I've updated Mageplaza Blog (which was the extension I've installed) from 4.1.3 to 4.1.4 and after updating also the Core to 1.4.12, the slider now appears.
